# Portfolio Profile Experiments

Use this notebook to prototype conservative, balanced, and aggressive portfolio rules before moving the logic into production modules.

In [1]:
from pathlib import Path
import sys

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

In [2]:
import pandas as pd

from ai_models.feature_builder import build_feature_table
from ai_models.quality_score_model import run_quality_score_model

feature_result = build_feature_table(
    fundamentals_path="data/fundamentals_cache.parquet",
    prices_path="data/prices_cache.parquet",
    treasury_path="data/treasury_yields_cache.parquet",
    benchmark_ticker="SPY",
)

features = feature_result.features.reset_index()
quality = run_quality_score_model(features)
universe = features.merge(quality, on="Ticker", how="left")
universe.head()

,Ticker,Momentum_12M,Volatility_63D,Drawdown_252D,Return_21D,Revenue_Growth_YoY_Pct,EBITDA_Margin,ROE,FreeCashFlow_Margin,Benchmark_Volatility,Benchmark_Trend,YC_10Y_2Y,YC_10Y_3M,YC_Inversion,YC_Volatility,QualityScore,QualityTier,Explanation
0,A,-0.094352,0.256801,-0.295212,-0.128762,6.728111,0.27898,0.19946,NaN,0.119467,0.183914,0.52,0.48,0.0,0.031328,53.558336,Neutral,"Return on equity, EBITDA margin, Revenue growth"
1,AAPL,0.170154,0.236271,-0.133331,-0.062606,6.425512,0.35100,1.52021,NaN,0.119467,0.183914,0.52,0.48,0.0,0.031328,68.177801,Strong,"Return on equity, EBITDA margin, Free cash flo..."
2,ABBV,-0.010978,0.271282,-0.149803,-0.105293,8.566763,0.47832,62.25000,NaN,0.119467,0.183914,0.52,0.48,0.0,0.031328,72.108711,Strong,"Return on equity, EBITDA margin, Revenue growth"
3,ABNB,0.038696,0.332178,-0.089899,0.041120,10.259413,0.21028,0.30233,NaN,0.119467,0.183914,0.52,0.48,0.0,0.031328,59.726650,Neutral,"Return on equity, Revenue growth, Free cash fl..."
4,ABT,-0.131591,0.272315,-0.209340,-0.049695,5.668653,0.27145,0.12961,NaN,0.119467,0.183914,0.52,0.48,0.0,0.031328,49.791031,Neutral,"EBITDA margin, Free cash flow margin, Revenue ..."

In [3]:
conservative = universe.sort_values(["QualityScore", "Volatility_63D"], ascending=[False, True]).head(15)
balanced = universe.sort_values(["QualityScore", "Momentum_12M"], ascending=[False, False]).head(15)
aggressive = universe.sort_values(["Momentum_12M", "QualityScore"], ascending=[False, False]).head(15)

conservative[["Ticker", "QualityScore", "Volatility_63D", "Momentum_12M"]].head(10)

    Ticker  QualityScore  Volatility_63D  Momentum_12M
301     MA     77.861883        0.245567     -0.074375
352   NVDA     77.595897        0.350602      0.545240
428    SPG     76.770328        0.185117      0.213211
483      V     74.968433        0.225438     -0.104815
504    WMB     74.374278        0.204677      0.311543
290    LLY     73.323992        0.404884      0.119338
218  GOOGL     73.209452        0.219305      0.906507
217   GOOG     73.017513        0.217591      0.873979
457    TPL     72.950368        0.475023      0.186463
29    AMGN     72.445617        0.304565      0.126887

In [4]:
balanced[["Ticker", "QualityScore", "Volatility_63D", "Momentum_12M"]].head(10)

    Ticker  QualityScore  Volatility_63D  Momentum_12M
301     MA     77.861883        0.245567     -0.074375
352   NVDA     77.595897        0.350602      0.545240
428    SPG     76.770328        0.185117      0.213211
483      V     74.968433        0.225438     -0.104815
504    WMB     74.374278        0.204677      0.311543
290    LLY     73.323992        0.404884      0.119338
218  GOOGL     73.209452        0.219305      0.906507
217   GOOG     73.017513        0.217591      0.873979
457    TPL     72.950368        0.475023      0.186463
29    AMGN     72.445617        0.304565      0.126887

In [5]:
aggressive[["Ticker", "QualityScore", "Volatility_63D", "Momentum_12M"]].head(10)

    Ticker  QualityScore  Volatility_63D  Momentum_12M
424   SNDK     40.416648        1.071133     12.195676
499    WDC     70.326408        0.831524      6.060453
96    CIEN     45.706176        0.715680      5.274988
435    STX     60.421884        0.786222      3.928543
336     MU     70.032416        0.701272      3.385560
198    FIX     62.772966        0.533634      3.229226
450    TER     55.324735        0.620999      2.363588
294   LRCX     70.377105        0.595626      1.996590
214    GLW     52.675894        0.626916      1.838855
497    WBD     37.157146        0.187346      1.633782